baseURL = 'https://www.nopeforge.org/'
languageCode = 'en-us'
title = 'Nope Forge'

[params]
  discord = "https://discord.gg/Ssg64PRJBE"
  github = "https://github.com/NopeForge"
  doc = "https://nopeforge.github.io/nope.gl"
  email = "contact@nopeforge.org"

  site_logo = '/img/logo.png'
  socials = [
    { name = "GitHub",   url = "https://github.com/NopeForge" },
    { name = "Mastodon", url = "https://fosstodon.org/@NopeForge" },
    { name = "Twitter",  url = "https://twitter.com/NopeForge" },
    { name = "YouTube",  url = "https://www.youtube.com/@NopeForge" },
    { name = "Discord",  url = "https://discord.gg/Ssg64PRJBE" },
    { name = "RSS",      url = "/news/index.xml" },
  ]
