baseURL = 'https://www.nope-foundry.org/'
languageCode = 'en-us'
title = 'Nope Foundry'

[params]
  discord = "https://discord.gg/Ssg64PRJBE"
  github = "https://github.com/NopeFoundry"
  doc = "https://nopefoundry.github.io/nope.gl"
  email = "contact@nope-foundry.org"

  site_logo = '/img/logo.png'
  socials = [
    { name = "GitHub",   url = "https://github.com/NopeFoundry" },
    { name = "Mastodon", url = "https://fosstodon.org/@NopeFoundry" },
    { name = "Twitter",  url = "https://twitter.com/NopeFoundry" },
    { name = "YouTube",  url = "https://www.youtube.com/@NopeFoundry" },
    { name = "Discord",  url = "https://discord.gg/Ssg64PRJBE" },
    { name = "RSS",      url = "/news/index.xml" },
  ]
